#!/usr/bin/env python3
"""Regenerate index.json from the flow files in this repository.

    python3 scripts/build-index.py            # rewrite index.json
    python3 scripts/build-index.py --check    # exit 1 if index.json is stale

index.json is what `iphone-use-mcp flow update` downloads first; every flow it
lists is then fetched by path and checked against the recorded sha256. Only
the CLI is the authority on flow validity (`iphone-use-mcp flow validate`);
this script does structural checks so a typo is caught before CI.
"""
import hashlib
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SLUG = re.compile(r"^[a-z0-9][a-z0-9_-]{0,63}$")
RISKS = {"read_only", "navigation", "side_effect"}


def fail(msg: str) -> None:
    print(f"error: {msg}", file=sys.stderr)
    sys.exit(1)


def load_json(path: Path):
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        fail(f"{path.relative_to(ROOT)}: invalid JSON ({exc})")


def main() -> None:
    check = "--check" in sys.argv[1:]
    apps = []
    flows = []
    for app_dir in sorted(p for p in ROOT.iterdir() if p.is_dir() and not p.name.startswith(".")):
        if app_dir.name in {"scripts"}:
            continue
        if not SLUG.match(app_dir.name):
            fail(f"app directory {app_dir.name!r} is not a lowercase slug")
        app_json = app_dir / "app.json"
        if not app_json.is_file():
            fail(f"{app_dir.name}/app.json is missing")
        app = load_json(app_json)
        if app.get("id") != app_dir.name:
            fail(f"{app_dir.name}/app.json id must be {app_dir.name!r}")
        apps.append({k: app[k] for k in ("id", "bundle", "name", "category", "description", "aliases") if k in app})
        for flow_path in sorted(app_dir.glob("*.json")):
            if flow_path.name == "app.json":
                continue
            stem = flow_path.stem
            if not SLUG.match(stem):
                fail(f"{flow_path.relative_to(ROOT)}: file name is not a lowercase slug")
            raw = flow_path.read_bytes()
            if not 1 <= len(raw) <= 64 * 1024:
                fail(f"{flow_path.relative_to(ROOT)}: must be 1..64 KiB")
            doc = load_json(flow_path)
            if doc.get("version") != 1:
                fail(f"{flow_path.relative_to(ROOT)}: version must be 1")
            for key in ("name", "steps"):
                if key not in doc:
                    fail(f"{flow_path.relative_to(ROOT)}: missing {key!r}")
            if doc.get("category") is not None and doc["category"] != app.get("category", doc["category"]):
                fail(f"{flow_path.relative_to(ROOT)}: category differs from app.json")
            if doc.get("risk") is not None and doc["risk"] not in RISKS:
                fail(f"{flow_path.relative_to(ROOT)}: risk must be one of {sorted(RISKS)}")
            if doc.get("app") is not None and app.get("bundle") and doc["app"] != app["bundle"]:
                fail(f"{flow_path.relative_to(ROOT)}: app bundle differs from app.json")
            flow_id = f"{app_dir.name}/{stem}"
            flows.append({
                "id": flow_id,
                "path": f"{flow_id}.json",
                "sha256": hashlib.sha256(raw).hexdigest(),
                "name": doc["name"],
                "description": doc.get("description"),
                "app": doc.get("app"),
                "category": doc.get("category"),
                "risk": doc.get("risk", "unknown"),
                "locale": doc.get("locale"),
                "inputs": sorted((doc.get("inputs") or {}).keys()),
                "steps": len(doc["steps"]),
                "verified": bool(doc.get("verified_on")),
            })
    index = {
        "version": 1,
        "$comment": "Generated by scripts/build-index.py — do not edit by hand. `iphone-use-mcp flow update` fetches this file, then every listed path, and verifies each sha256.",
        "flows": flows,
        "apps": apps,
    }
    rendered = json.dumps(index, ensure_ascii=False, indent=2) + "\n"
    target = ROOT / "index.json"
    if check:
        current = target.read_text(encoding="utf-8") if target.exists() else ""
        if current != rendered:
            fail("index.json is stale; run python3 scripts/build-index.py")
        print(f"index.json is current ({len(flows)} flows, {len(apps)} apps)")
        return
    target.write_text(rendered, encoding="utf-8")
    print(f"wrote index.json ({len(flows)} flows, {len(apps)} apps)")


if __name__ == "__main__":
    main()
